### ISSUE TITLE
npm i fails on unknown protocol

### ISSUE THREAD

**Issue by golyalpha** [rot1024/cesium-react#5]
Running `npm i` fails with `npm:webpack@^3.11.0 - Unknown protocol npm` on the webpack-v3 requirement.

Any workarounds available?

**Comment by rot1024** [comment]
Please use [yarn](https://yarnpkg.com/lang/en/) instead of npm. This project uses yarn.

**Comment by golyalpha** [comment]
Might be appropriate to update the README.md in that case. I was just following the instructions there.

**Comment by rot1024** [comment]
This issue no longer occurs because the yarn's protocol has not been used. npm is also usable at present.
